In [6]:
import numpy as np


arr = np.random.randint(0,255, size=(1920,1080), dtype=np.uint8)
print(arr.shape)
print(arr)

(1920, 1080)
[[146   7 129 ...  96 170 111]
 [ 78   2  52 ...   2 254  88]
 [156 254 143 ...  48 103 182]
 ...
 [149  83 216 ...  15  40  56]
 [ 79 160  25 ... 170 109 191]
 [ 44  83 224 ... 157 134  95]]


In [3]:
import cv2
import numpy as np
import ffmpeg

process = (
    ffmpeg
        .input('pipe:', format='rawvideo', pix_fmt='gray', s='1920x1080')
        .output('OUTPUT.mp4', pix_fmt='gray', vcodec='libx265', r=1)
        .overwrite_output()
        .run_async(pipe_stdin=True)
)
for i in range(100):
    arr = np.random.randint(0,255, size=(1920,1080), dtype=np.uint8)
    process.stdin.write(arr.tobytes())
process.stdin.close()
process.wait()



0