In [6]:
import numpy as np


arr = np.random.randint(0,255, size=(1920,1080), dtype=np.uint8)
print(arr.shape)
print(arr)

(1920, 1080)
[[146   7 129 ...  96 170 111]
 [ 78   2  52 ...   2 254  88]
 [156 254 143 ...  48 103 182]
 ...
 [149  83 216 ...  15  40  56]
 [ 79 160  25 ... 170 109 191]
 [ 44  83 224 ... 157 134  95]]


In [3]:
import cv2
import numpy as np
import ffmpeg
import time


# process = (
#     ffmpeg
#         .input('pipe:', format='rawvideo', pix_fmt='gray', s='1920x1080', r=1)
#         .output('OUTPUT.mp4', pix_fmt='gray', vcodec='libx265', r=1)
#         .overwrite_output()
#         .run_async(pipe_stdin=True)
# )

# # for i in range(100):
# #     arr = np.random.randint(0,255, size=(1920,1080), dtype=np.uint8)
# #     process.stdin.write(arr)

# arr = np.random.randint(0,256, size=20736000, dtype=np.uint8)
# process.stdin.write(arr)

# process.stdin.close()
# process.wait()



bin = np.fromfile(str(file), dtype=np.uint8)
bin = np.unpackbits(bin).reshape(-1,1)
framesize = 259200

filler_bytes = framesize - (bin.size // framesize)
if filler_bytes != 0:
    zeros = np.zeros(filler_bytes, dtype=np.uint8)
    bin = np.append(bin, zeros)
    del zeros

process = (
    ffmpeg
        .input('pipe:', format='rawvideo', pix_fmt='gray', s='1920x1080', r=1)
        .output('OUTPUT.mp4', pix_fmt='gray', vcodec='libx265', r=1)
        .overwrite_output()
        .run_async(pipe_stdin=True)
)
process.stdin.write(bin)
process.stdin.close()
process.wait()


0

In [7]:
import subprocess
from pathlib import Path


file = Path('C:/dev/youbit/OUTPUT.mp4')
cmd = "ffmpeg -i {} -r 1/1 {}/frame%d.png".format(str(file), str(file.parent))
subprocess.Popen(cmd, shell=True).wait()

0