In [6]:
import numpy as np


arr = np.random.randint(0,255, size=(1920,1080), dtype=np.uint8)
print(arr.shape)
print(arr)

(1920, 1080)
[[146   7 129 ...  96 170 111]
 [ 78   2  52 ...   2 254  88]
 [156 254 143 ...  48 103 182]
 ...
 [149  83 216 ...  15  40  56]
 [ 79 160  25 ... 170 109 191]
 [ 44  83 224 ... 157 134  95]]


In [3]:
import cv2
import numpy as np
import ffmpeg
import time
import cProfile

pr = cProfile.Profile()
pr.enable()


# process = (
#     ffmpeg
#         .input('pipe:', format='rawvideo', pix_fmt='gray', s='1920x1080', r=1)
#         .output('OUTPUT.mp4', pix_fmt='gray', vcodec='libx265', r=1)
#         .overwrite_output()
#         .run_async(pipe_stdin=True)
# )

# # for i in range(100):
# #     arr = np.random.randint(0,255, size=(1920,1080), dtype=np.uint8)
# #     process.stdin.write(arr)

# arr = np.random.randint(0,256, size=20736000, dtype=np.uint8)
# process.stdin.write(arr)

# process.stdin.close()
# process.wait()



framesize = 2073600

bin = np.fromfile('C:/monke.mp4', dtype=np.uint8)
bin = np.unpackbits(bin).reshape(-1,1) #1bpp
zeros = np.zeros(framesize - (bin.size % framesize), dtype=np.uint8)
bin = np.append(bin, zeros)

bin[bin != 0] = 255

process = (
    ffmpeg
        .input('pipe:', format='rawvideo', pix_fmt='gray', s='1920x1080', r=1)
        .output('OUTPUT.mp4', pix_fmt='gray', vcodec='libx264', crf=0, r=1)
        .overwrite_output()
        .run_async(pipe_stdin=True)
)
process.stdin.write(bin)
process.stdin.close()
process.wait()


pr.print_stats(sort='tottime')
pr.disable()



         1183 function calls (1080 primitive calls) in 51.333 seconds

   Ordered by: internal time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1   33.952   33.952   33.952   33.952 {method 'write' of '_io.BufferedWriter' objects}
        1   11.991   11.991   11.991   11.991 18931530.py:38(<cell line: 38>)
      4/2    3.197    0.799    3.197    1.599 {built-in method numpy.core._multiarray_umath.implement_array_function}
        1    1.051    1.051    1.051    1.051 {built-in method _winapi.CreateProcess}
        1    0.578    0.578    0.578    0.578 {built-in method _winapi.WaitForSingleObject}
        1    0.298    0.298    2.903    2.903 18931530.py:36(<cell line: 36>)
        1    0.240    0.240    0.240    0.240 {built-in method numpy.fromfile}
        1    0.015    0.015    0.608    0.608 18931530.py:34(<cell line: 34>)
       11    0.002    0.000    0.002    0.000 {built-in method builtins.compile}
     50/6    0.002    0.000    0.002    0.

In [13]:
from pathlib import Path
import numpy as np

path = Path('E:/devy/pop')

print(
    path.exists(),
    path.is_dir(),
    path.is_file()
)

arr = np.array([1,2,3,4,5])

arr.tofile(path)

False False False


FileNotFoundError: [Errno 2] No such file or directory: 'E:\\devy\\pop'

In [5]:
import numpy as np

arr =np.array([1,2,3,4,5,])


print(f'sdfsdfsdf {1}')

sdfsdfsdf 1


In [29]:
arr = [1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0] + ([1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0]*100000)

class Testy:
    def __init__(self, arr):
        self.arr = arr

    def __iter__(self):
        self.index = 0
        return self
    
    def __next__(self):
        try:
            if not ((self.index-11) % 17):
                result = self.arr[self.index+1]
                self.index += 2
            else:
                result =  self.arr[self.index]
                self.index += 1
            return result
        except IndexError:
            raise StopIteration

testy = Testy(arr)
newarr = []
for i in testy:
    newarr.append(i)

# print(newarr)

if not all(newarr):
    print('houston weve got a problem')
else:
    print('all good!')


all good!


In [1]:
from youbit.video import VideoDecoder

decoder = VideoDecoder('E:/INPUTFORYT.mp4')

print(list(decoder))



e:\dev\youbit\youbit\video.py:55: UserWarning: Video passed to VideoDecoder has a framerate of 1. This probably means the video did not go though YouTube. Beware that this decoder will only work on videos that have gone through YouTube's own compression.
  warnings.warn(f"Video passed to {type(self).__name__} has a framerate of 1. This probably means the video did not go though YouTube. Beware that this decoder will only work on videos that have gone through YouTube's own compression.")


[array([255, 255, 255, ..., 255, 160, 255], dtype=uint8), array([160, 160, 160, ..., 255, 160,  95], dtype=uint8), array([160, 255, 160, ...,   0, 160,   0], dtype=uint8), array([255,  95, 160, ..., 160, 160,   0], dtype=uint8), array([255,  95,  95, ...,   0,  95, 160], dtype=uint8), array([  0, 255, 160, ...,   0, 160,   0], dtype=uint8), array([255,   0, 255, ..., 160, 160, 160], dtype=uint8), array([160,   0,   0, ..., 160, 255, 255], dtype=uint8), array([255, 255, 160, ...,  95, 160, 255], dtype=uint8), array([  0, 255, 160, ...,  95, 160,   0], dtype=uint8), array([ 95,   0, 255, ..., 160,   0, 255], dtype=uint8), array([  0, 255, 255, ...,   0, 255, 160], dtype=uint8), array([  0, 255, 160, ..., 255, 255, 160], dtype=uint8), array([ 0,  0,  0, ...,  0,  0, 95], dtype=uint8), array([  0, 255, 160, ...,   0,   0, 255], dtype=uint8), array([255, 255,   0, ..., 255, 255, 160], dtype=uint8), array([ 95, 160, 160, ..., 255, 160,   0], dtype=uint8), array([ 95, 160,   0, ...,   0, 160,

In [5]:
from youbit.video import VideoDecoder, VideoEncoder
import numpy as np
from pathlib import Path


arr = [i for i in range(256)] * 8100 # makes the length exactly 2073600, or the sum of pixels in a 1920x1080 frame. 
arr = np.array(arr, dtype=np.uint8)

with VideoEncoder(Path('E:/what/test____.mp4')) as encoder:
    encoder.feed(arr)



In [2]:
from youbit.video import VideoDecoder, VideoEncoder
import numpy as np
from pathlib import Path

# with VideoDecoder('E:/dev/youbit/test2.jpg.mkv') as decoder:
#     listy = decoder.get_all()

# print(listy)

print(list(VideoDecoder('E:/dev/youbit/test2.jpg.mkv')))

[array([235, 255, 246, ..., 235, 151, 255], dtype=uint8), array([170, 171, 143, ..., 255, 141, 118], dtype=uint8), array([158, 255, 137, ...,   0, 162,   0], dtype=uint8), array([227,  91, 170, ..., 156, 178,   0], dtype=uint8), array([247, 100,  91, ...,   1,  98, 176], dtype=uint8), array([  0, 243, 139, ...,  22, 171,   0], dtype=uint8), array([255,  20, 255, ..., 158, 163, 173], dtype=uint8), array([154,   9,   2, ..., 179, 255, 255], dtype=uint8), array([255, 255, 144, ...,  88, 171, 250], dtype=uint8), array([ 10, 240, 137, ...,  70, 168,  17], dtype=uint8), array([ 76,  29, 228, ..., 172,   2, 254], dtype=uint8), array([ 95, 137,   0, ..., 147, 241, 241], dtype=uint8), array([ 12, 255, 253, ...,   5, 249, 162], dtype=uint8), array([ 15, 231, 140, ..., 245, 255, 158], dtype=uint8), array([ 16,  22,   1, ...,  14,   0, 100], dtype=uint8), array([ 35, 220, 153, ...,  19,  15, 255], dtype=uint8), array([255, 255,   0, ..., 255, 255, 147], dtype=uint8), array([ 77, 177, 160, ..., 255